import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app/app.dart';
import 'features/notifications/data/notification_service.dart';

/// ENTRY POINT
/// Initialises Firebase, then starts the app inside a Riverpod [ProviderScope].
///
/// Firebase reads its config from the platform files generated by your own
/// Firebase project (e.g. android/app/google-services.json) — see README.
/// These are gitignored and never committed.
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  // Handle FCM messages received while the app is backgrounded/terminated.
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  runApp(const ProviderScope(child: App()));
}
